### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'EleGANt/faceutils/mask/resnet.pth'

### ISSUE THREAD

**Issue by watertianyi** [Chenyu-Yang-2000/EleGANt#1]

**Comment by Chenyu-Yang-2000** [comment]
Hello @hande6688, thanks for checkout out our work.

We have put the instructions and links of the required checkpoints at [https://github.com/Chenyu-Yang-2000/EleGANt/blob/main/assets/docs/prepare.md](url), you can check if you have followed those steps to finish the preparation. You can also download this checkpoint directly from [https://github.com/wtjiang98/PSGAN/blob/master/faceutils/mask/resnet.pth](url).

**Comment by watertianyi** [comment]
@Chenyu-Yang-2000
Does the model image only support 361X361, does it not support resolution 512X512 or 1024X1024?
