### ISSUE TITLE
如何转换为onnx模型

### ISSUE THREAD

**Issue by ZTMIDGO** [Chenyu-Yang-2000/EleGANt#14]
你好，请问我要如何转换为onnx模型？

**Comment by ZTMIDGO** [comment]
device = 'cpu'
        c = torch.randn(1, 3, 256, 256, requires_grad=True).to(device)
        s = torch.randn(1, 3, 256, 256, requires_grad=True).to(device)

        mask_c = torch.randn(1, 2, 256, 256, requires_grad=True).to(device)
        mask_s = torch.randn(1, 2, 256, 256, requires_grad=True).to(device)

        diff_c = torch.randn(1, 136, 256, 256, requires_grad=True).to(device)
        diff_s = torch.randn(1, 136, 256, 256, requires_grad=True).to(device)

        lms_c = torch.randn(1, 68, 2, requires_grad=True).to(device)
        lms_s = torch.randn(1, 68, 2, requires_grad=True).to(device)

        input = ['c', 's', 'mask_c', 'mask_s', 'diff_c', 'diff_s', 'lms_c', 'lms_s']
        output = ['output']

        torch.onnx.export(self.solver.G, (c, s, mask_c, mask_s, diff_c, diff_s, lms_c, lms_s), 'model.onnx', verbose=True, 
        opset_version=15, input_names=input, output_names=output)

无法使用以上代码转换为onnx：
 Exporting the operator inverse to ONNX opset version 15 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

希望可以指教一下如何解决问题。

**Comment by Fcucgvhhhvjv** [comment]
@ZTMIDGO 

> ```
>     device = 'cpu'
>     c = torch.randn(1, 3, 256, 256, requires_grad=True).to(device)
>     s = torch.randn(1, 3, 256, 256, requires_grad=True).to(device)
> 
>     mask_c = torch.randn(1, 2, 256, 256, requires_grad=True).to(device)
>     mask_s = torch.randn(1, 2, 256, 256, requires_grad=True).to(device)
> 
>     diff_c = torch.randn(1, 136, 256, 256, requires_grad=True).to(device)
>     diff_s = torch.randn(1, 136, 256, 256, requires_grad=True).to(device)
> 
>     lms_c = torch.randn(1, 68, 2, requires_grad=True).to(device)
>     lms_s = torch.randn(1, 68, 2, requires_grad=True).to(device)
> 
>     input = ['c', 's', 'mask_c', 'mask_s', 'diff_c', 'diff_s', 'lms_c', 'lms_s']
>     output = ['output']
> 
>     torch.onnx.export(self.solver.G, (c, s, mask_c, mask_s, diff_c, diff_s, lms_c, lms_s), 'model.onnx', verbose=True, 
>     opset_version=15, input_names=input, output_names=output)
> ```
> 
> Cannot convert to onnx using the above code: Exporting the operator inverse to ONNX opset version 15 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
> 
> Hope you can teach me how to solve the problem.

I don't know about the code but this error "Exporting the operator inverse to ONNX opset version 15 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub " i think can be fixed simply by using pytorch nightly

**Comment by ZTMIDGO** [comment]
@Fcucgvhhhvjv Based on the support list listed by pytorch https://pytorch.org/docs/stable/onnx_supported_aten_ops.html, perhaps only replacing the operator will solve the problem

**Comment by Holmes2002** [comment]
@ZTMIDGO Hi, I have been struggling to convert EleGANt to onnx. I was success how ever its performance was bad

<img width="1042" height="348" alt="Image" src="https://github.com/user-attachments/assets/9f798c08-1509-4ffe-9550-bd0b090a0e8d" />

I just replace torch.inverse in TPS by numpy. Any ideas or advices for me ?
